---
deployment:
  tasks:
    - export DEPLOYPATH=/home/veterina/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp -R imagenes-landing $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
